name: Build & Publish VWA Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/crud-web-apps/volumes/**
      - components/crud-web-apps/common/**
      - releasing/version/VERSION

env:
  DOCKER_USER: rahul1181
  IMG: rahul1181/volumes-web-app
  ARCH: linux/ppc64le

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-20.04-ppc64le
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push multi-arch docker image
      run: |
        cd components/crud-web-apps/volumes
        export IMG=rahul1181/volumes-web-app
        sudo su -
        apt-get install make
        make docker-build-push-multi-arch

    - name: Build and push latest multi-arch docker image
      if: github.ref == 'refs/heads/master'
      run: |
        export TAG=latest
        cd components/crud-web-apps/volumes
        make docker-build-push-multi-arch

    - name: Build and push multi-arch docker image on Version change
      id: version
      if: steps.filter.outputs.version == 'true'
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/crud-web-apps/volumes
        make docker-build-push-multi-arch
